version: "3.5"

services:

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    env_file: configuracionInfluxGF.env
    volumes:
      - ./influxdb/data:/var/lib/influxdb
    ports:
      - 8086:8086
    restart: always

  grafana:
    build: grafana
    env_file: configuracionInfluxGF.env
    links:
      - influxdb
    ports:
      - '80:3000' #Puerto base de grafana

  app-cliente:
    build: .
    container_name: app_cliente
    depends_on:
      - influxdb
    ports:
      - 5000:5000
