version: "3.5"

services:

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_USER: user
      INFLUXDB_USER_PASSWORD: password
      INFLUXDB_DB: my_db
    volumes:
      - ./influxdb/:/var/lib/influxdb
    ports:
      - 8086:8086
    restart: always

  grafana:
    build: ./grafana/
    container_name: grafana
    ports:
      - 80:3000

  app:
    build: .
    container_name: app
    depends_on:
      - influxdb
